siblh\menuBundle\Entity\BlhAnalisisMicrobiologico:
    type: entity
    table: blh_analisis_microbiologico
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: SEQUENCE
        codigoAnalisisMicrobiologico:
            type: string
            length: 11
            fixed: false
            nullable: false
            column: codigo_analisis_microbiologico
        coliformesTotales:
            type: string
            length: 8
            fixed: false
            nullable: false
            column: coliformes_totales
        control:
            type: string
            length: 8
            fixed: false
            nullable: false
        situacion:
            type: string
            length: 9
            fixed: false
            nullable: false
    manyToOne:
        idFrascoProcesado:
            targetEntity: BlhFrascoProcesado
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_frasco_procesado:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
