siblh\menuBundle\Entity\BlhAcidez:
    type: entity
    table: blh_acidez
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: SEQUENCE
        codigoAnalisisFisicoQuimico:
            type: string
            length: 11
            fixed: false
            nullable: false
            column: codigo_analisis_fisico_quimico
        acidez1:
            type: integer
            unsigned: false
            nullable: false
        acidez2:
            type: integer
            unsigned: false
            nullable: false
        acidez3:
            type: integer
            unsigned: false
            nullable: false
        factor:
            type: decimal
            nullable: false
        resultado:
            type: decimal
            nullable: false
        mediaAcidez:
            type: decimal
            nullable: false
            column: media_acidez
    manyToOne:
        idAnalisisFisicoQuimico:
            targetEntity: BlhAnalisisFisicoQuimico
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_analisis_fisico_quimico:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
