siblh\menuBundle\Entity\BlhAnalisisSensorial:
    type: entity
    table: blh_analisis_sensorial
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: SEQUENCE
        codigoAnalisisFisicoQuimico:
            type: string
            length: 11
            fixed: false
            nullable: false
            column: codigo__analisis_fisico_quimico
        embalaje:
            type: string
            length: 9
            fixed: false
            nullable: true
        suciedad:
            type: string
            length: 9
            fixed: false
            nullable: true
        color:
            type: string
            length: 9
            fixed: false
            nullable: true
        flavor:
            type: string
            length: 9
            fixed: false
            nullable: true
        observacion:
            type: string
            length: 30
            fixed: false
            nullable: true
    manyToOne:
        idAnalisisFisicoQuimico:
            targetEntity: BlhAnalisisFisicoQuimico
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_analisis_fisico_quimico:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
