siblh\menuBundle\Entity\BlhBancoDeLeche:
    type: entity
    table: blh_banco_de_leche
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: SEQUENCE
        codigoBancoDeLeche:
            type: string
            length: 6
            fixed: false
            nullable: false
            column: codigo_banco_de_leche
        estadoBanco:
            type: string
            length: 8
            fixed: false
            nullable: false
            column: estado_banco
    manyToOne:
        idEstablecimiento:
            targetEntity: CtlEstablecimiento
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_establecimiento:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
