siblh\menuBundle\Entity\BlhCrematocrito:
    type: entity
    table: blh_crematocrito
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: SEQUENCE
        codigoAnalisisFisicoQuimico:
            type: string
            length: 11
            fixed: false
            nullable: false
            column: codigo_analisis_fisico_quimico
        crema1:
            type: decimal
            nullable: false
        crema2:
            type: decimal
            nullable: false
        crema3:
            type: decimal
            nullable: false
        ct1:
            type: decimal
            nullable: false
        ct2:
            type: decimal
            nullable: false
        ct3:
            type: decimal
            nullable: false
        mediaCrema:
            type: decimal
            nullable: false
            column: media_crema
        mediaCt:
            type: decimal
            nullable: false
            column: media_ct
        porcentajeCrema:
            type: decimal
            nullable: false
            column: porcentaje_crema
        kilocalorias:
            type: decimal
            nullable: false
    manyToOne:
        idAnalisisFisicoQuimico:
            targetEntity: BlhAnalisisFisicoQuimico
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_analisis_fisico_quimico:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
