siblh\menuBundle\Entity\BlhEstado:
    type: entity
    table: blh_estado
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: SEQUENCE
        nombreEstado:
            type: string
            length: 13
            fixed: false
            nullable: false
            column: nombre_estado
    lifecycleCallbacks: {  }
