siblh\menuBundle\Entity\BlhHistorialClinico:
    type: entity
    table: blh_historial_clinico
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: SEQUENCE
        amenorrea:
            type: integer
            unsigned: false
            nullable: true
        controlPrenatal:
            type: string
            length: 2
            fixed: false
            nullable: false
            column: control_prenatal
        lugarControl:
            type: string
            length: 25
            fixed: false
            nullable: true
            column: lugar_control
        numeroControl:
            type: integer
            unsigned: false
            nullable: true
            column: numero_control
        fechaUltimaRegla:
            type: date
            nullable: true
            column: fecha_ultima_regla
        fechaParto:
            type: date
            nullable: false
            column: fecha_parto
        lugarParto:
            type: string
            length: 30
            fixed: false
            nullable: false
            column: lugar_parto
        patologiaEmbarazo:
            type: string
            length: 20
            fixed: false
            nullable: true
            column: patologia_embarazo
        periodoIntergenesico:
            type: integer
            unsigned: false
            nullable: false
            column: periodo_intergenesico
        fechaPartoAnterior:
            type: date
            nullable: false
            column: fecha_parto_anterior
        formulaObstetrica:
            type: string
            length: 18
            fixed: false
            nullable: false
            column: formula_obstetrica
    manyToOne:
        idDonante:
            targetEntity: BlhDonante
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_donante:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
