siblh\menuBundle\Entity\BlhHistoriaActual:
    type: entity
    table: blh_historia_actual
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: SEQUENCE
        pesoDonante:
            type: decimal
            nullable: false
            column: peso_donante
        tallaDonante:
            type: decimal
            nullable: false
            column: talla_donante
        medicamento:
            type: string
            length: 50
            fixed: false
            nullable: true
        habitoToxico:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: habito_toxico
        motivoDonacion:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: motivo_donacion
        patologiaDonante:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: patologia_donante
        imc:
            type: decimal
            nullable: false
    manyToOne:
        idDonante:
            targetEntity: BlhDonante
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_donante:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
