siblh\menuBundle\Entity\BlhIngresoReceptor:
    type: entity
    table: blh_ingreso_receptor
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: SEQUENCE
        pesoReceptor:
            type: decimal
            nullable: false
            column: peso_receptor
        duracionCpap:
            type: integer
            unsigned: false
            nullable: true
            column: duracion_cpap
        clasificacionLubchengo:
            type: string
            length: 3
            fixed: false
            nullable: false
            column: clasificacion_lubchengo
        diagnosticoIngreso:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: diagnostico_ingreso
        duracionNpt:
            type: integer
            unsigned: false
            nullable: true
            column: duracion_npt
        apgar:
            type: integer
            unsigned: false
            nullable: true
        edadGestFur:
            type: decimal
            nullable: false
            column: edad_gest_fur
        duracionVentilacion:
            type: integer
            unsigned: false
            nullable: true
            column: duracion_ventilacion
        edadGestBallard:
            type: decimal
            nullable: false
            column: edad_gest_ballard
        pc:
            type: decimal
            nullable: false
        tallaIngreso:
            type: decimal
            nullable: true
            column: talla_ingreso
    manyToOne:
        idReceptor:
            targetEntity: BlhReceptor
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_receptor:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
