siblh\menuBundle\Entity\BlhInformacionPublica:
    type: entity
    table: blh_informacion_publica
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: SEQUENCE
        documento:
            type: blob
            nullable: false
        tipo:
            type: string
            length: 15
            fixed: false
            nullable: false
        nombreDocumento:
            type: string
            length: 30
            fixed: false
            nullable: false
            column: nombre_documento
        fechaPublicacion:
            type: date
            nullable: false
            column: fecha_publicacion
    manyToOne:
        idBancoDeLeche:
            targetEntity: BlhBancoDeLeche
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_banco_de_leche:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
