siblh\menuBundle\Entity\BlhLoteAnalizado:
    type: entity
    table: blh_lote_analizado
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: SEQUENCE
        codigoLoteAnalizado:
            type: string
            length: 9
            fixed: false
            nullable: false
            column: codigo_lote_analizado
        fechaAnalisisFisicoQuimico:
            type: date
            nullable: false
            column: fecha_analisis_fisico_quimico
    lifecycleCallbacks: {  }
