siblh\menuBundle\Entity\BlhOpcionMenu:
    type: entity
    table: blh_opcion_menu
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: SEQUENCE
        nombreOpcion:
            type: string
            length: 15
            fixed: false
            nullable: false
            column: nombre_opcion
    manyToOne:
        idMenu:
            targetEntity: BlhMenu
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_menu:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
