siblh\menuBundle\Entity\BlhReceptor:
    type: entity
    table: blh_receptor
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: SEQUENCE
        codigoReceptor:
            type: string
            length: 12
            fixed: false
            nullable: true
            column: codigo_receptor
        fechaRegistroBlh:
            type: date
            nullable: true
            column: fecha_registro_blh
        procedencia:
            type: string
            length: 20
            fixed: false
            nullable: true
        estadoReceptor:
            type: string
            length: 8
            fixed: false
            nullable: true
            column: estado_receptor
        edadDias:
            type: integer
            unsigned: false
            nullable: false
            column: edad_dias
    manyToOne:
        idBancoDeLeche:
            targetEntity: BlhBancoDeLeche
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_banco_de_leche:
                    referencedColumnName: id
            orphanRemoval: false
        idPaciente:
            targetEntity: MntPaciente
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_paciente:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
