siblh\menuBundle\Entity\BlhRol:
    type: entity
    table: blh_rol
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: SEQUENCE
        nombreRol:
            type: string
            length: 15
            fixed: false
            nullable: false
            column: nombre_rol
        descripcionRol:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: descripcion_rol
    lifecycleCallbacks: {  }
