siblh\menuBundle\Entity\BlhSolicitud:
    type: entity
    table: blh_solicitud
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: SEQUENCE
        codigoSolicitud:
            type: string
            length: 14
            fixed: false
            nullable: false
            column: codigo_solicitud
        volumenPorDia:
            type: decimal
            nullable: false
            column: volumen_por_dia
        acidezNecesaria:
            type: string
            length: 9
            fixed: false
            nullable: false
            column: acidez_necesaria
        caloriasNecesarias:
            type: string
            length: 15
            fixed: false
            nullable: false
            column: calorias_necesarias
        pesoDia:
            type: decimal
            nullable: false
            column: peso_dia
        volumenPorToma:
            type: decimal
            nullable: false
            column: volumen_por_toma
        tomaPorDia:
            type: integer
            unsigned: false
            nullable: false
            column: toma_por_dia
        fechaSolicitud:
            type: date
            nullable: false
            column: fecha_solicitud
        cuna:
            type: integer
            unsigned: false
            nullable: false
        estado:
            type: string
            length: 1
            fixed: false
            nullable: false
        responsable:
            type: string
            length: 30
            fixed: false
            nullable: true
    manyToOne:
        idGrupoSolicitud:
            targetEntity: BlhGrupoSolicitud
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_grupo_solicitud:
                    referencedColumnName: id
            orphanRemoval: false
        idReceptor:
            targetEntity: BlhReceptor
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_receptor:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
