siblh\menuBundle\Entity\BlhTemperaturaEnfriamiento:
    type: entity
    table: blh_temperatura_enfriamiento
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: SEQUENCE
        temperaturaE:
            type: integer
            unsigned: false
            nullable: false
            column: temperatura_e
    manyToOne:
        idPasteurizacion:
            targetEntity: BlhPasteurizacion
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_pasteurizacion:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
