siblh\menuBundle\Entity\CltMunicipio:
    type: entity
    table: clt_municipio
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: SEQUENCE
        nombre:
            type: string
            length: 150
            fixed: false
            nullable: false
        codigoCnr:
            type: string
            length: 5
            fixed: false
            nullable: true
            column: codigo_cnr
        abreviatura:
            type: string
            length: 5
            fixed: false
            nullable: true
    manyToOne:
        idDepartamento:
            targetEntity: CtlDepartamento
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_departamento:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
