siblh\menuBundle\Entity\CtlDepartamento:
    type: entity
    table: ctl_departamento
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: SEQUENCE
        nombre:
            type: string
            length: 150
            fixed: false
            nullable: false
        codigoCnr:
            type: string
            length: 5
            fixed: false
            nullable: true
            column: codigo_cnr
        abreviatura:
            type: string
            length: 5
            fixed: false
            nullable: true
    lifecycleCallbacks: {  }
