siblh\menuBundle\Entity\CtlEstablecimiento:
    type: entity
    table: ctl_establecimiento
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: SEQUENCE
        nombre:
            type: string
            length: 150
            fixed: false
            nullable: false
        direccion:
            type: string
            length: 250
            fixed: false
            nullable: false
        telefono:
            type: string
            length: 15
            fixed: false
            nullable: false
        fax:
            type: string
            length: 15
            fixed: false
            nullable: true
    lifecycleCallbacks: {  }
