siblh\menuBundle\Entity\FosUserUser:
    type: entity
    table: fos_user_user
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: SEQUENCE
        username:
            type: string
            length: 255
            fixed: false
            nullable: false
        usernameCanonical:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: username_canonical
        email:
            type: string
            length: 255
            fixed: false
            nullable: false
        emailCanonical:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: email_canonical
        enable:
            type: boolean
            nullable: false
        salt:
            type: string
            length: 255
            fixed: false
            nullable: true
        password:
            type: string
            length: 255
            fixed: false
            nullable: true
        lastLogin:
            type: date
            nullable: true
            column: last_login
        locked:
            type: boolean
            nullable: true
        expired:
            type: boolean
            nullable: true
        expiresAt:
            type: date
            nullable: true
            column: expires_at
        confirmationToken:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: confirmation_token
        passwordRequestedAt:
            type: date
            nullable: true
            column: password_requested_at
        roles:
            type: text
            nullable: true
        credentialsExpired:
            type: boolean
            nullable: true
            column: credentials_expired
        credentialsExpireAt:
            type: date
            nullable: true
            column: credentials_expire_at
        createdAt:
            type: date
            nullable: true
            column: created_at
        updateAt:
            type: date
            nullable: true
            column: update_at
        dateOfBirth:
            type: date
            nullable: true
            column: date_of_birth
        firstname:
            type: string
            length: 64
            fixed: false
            nullable: true
        lastname:
            type: string
            length: 64
            fixed: false
            nullable: true
        website:
            type: string
            length: 64
            fixed: false
            nullable: true
        biography:
            type: string
            length: 255
            fixed: false
            nullable: true
        gender:
            type: string
            length: 1
            fixed: false
            nullable: true
        locale:
            type: string
            length: 8
            fixed: false
            nullable: true
        timezone:
            type: string
            length: 64
            fixed: false
            nullable: true
        phone:
            type: string
            length: 64
            fixed: false
            nullable: true
        facebookUid:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: facebook_uid
        facebookName:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: facebook_name
        facebookData:
            type: text
            nullable: true
            column: facebook_data
        twitterUid:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: twitter_uid
        twitterName:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: twitter_name
        twitterData:
            type: text
            nullable: true
            column: twitter_data
        gplusUid:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: gplus_uid
        gplusName:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: gplus_name
        gplusData:
            type: text
            nullable: true
            column: gplus_data
        token:
            type: string
            length: 255
            fixed: false
            nullable: true
        twoStepCode:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: two_step_code
    manyToOne:
        idEstablecimiento:
            targetEntity: CtlEstablecimiento
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_establecimiento:
                    referencedColumnName: id
            orphanRemoval: false
        idRol:
            targetEntity: BlhRol
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_rol:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
