siblh\menuBundle\Entity\FosUserGroup:
    type: entity
    table: fos_user_group
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: SEQUENCE
        name:
            type: string
            length: 255
            fixed: false
            nullable: false
        roles:
            type: text
            nullable: true
    lifecycleCallbacks: {  }
