siblh\menuBundle\Entity\MntExpediente:
    type: entity
    table: mnt_expediente
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: SEQUENCE
        numero:
            type: string
            length: 10
            fixed: false
            nullable: true
    manyToOne:
        idPaciente:
            targetEntity: MntPaciente
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_paciente:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
