siblh\menuBundle\Entity\MntPaciente:
    type: entity
    table: mnt_paciente
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: SEQUENCE
        horaNacimiento:
            type: date
            nullable: true
            column: hora_nacimiento
        fechaNacimiento:
            type: date
            nullable: false
            column: fecha_nacimiento
        primerNombre:
            type: string
            length: 25
            fixed: false
            nullable: false
            column: primer_nombre
        segundoNombre:
            type: string
            length: 25
            fixed: false
            nullable: true
            column: segundo_nombre
        tercerNombre:
            type: string
            length: 25
            fixed: false
            nullable: true
            column: tercer_nombre
        primerApellido:
            type: string
            length: 25
            fixed: false
            nullable: false
            column: primer_apellido
        segundoApelido:
            type: string
            length: 25
            fixed: false
            nullable: true
            column: segundo_apelido
        direccion:
            type: string
            length: 100
            fixed: false
            nullable: false
    manyToOne:
        idMunicipioDomicilio:
            targetEntity: CltMunicipio
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_municipio_domicilio:
                    referencedColumnName: id
            orphanRemoval: false
        idSexo:
            targetEntity: CtlSexo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_sexo:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
