jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    #acl:
    #    connection: default
    #Definiendo Roles SIBLH    
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_LABORATORISTA: [ROLE_LABORATORISTA]
        ROLE_SECRETARIA: [ROLE_SECRETARIA]
        ROLE_JEFE: [ROLE_JEFE]
        ROLE_PEDIATRA: [ROLE_PEDIATRA]
        SONATA:
            #- ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT  # if you are using acl then this line must be commented

    providers:
        fos_userbundle:
            id: fos_user.user_manager
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        
    firewalls:
        # -> custom firewall for the admin area of the URL
        admin:
            switch_user:        true
            context:            user
            pattern:            /admin(.*)
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
                use_referer:    true
               # default_target_path:  /admin/dashboard
                default_target_path:  /inicio
               
                #AGREGADO
                #always_use_default_target_path: true
            logout:
                path:           /admin/logout
                target:         /admin/login
                #corrigiendo error de logout
                invalidate_session: false
            anonymous:    true
            
        # -> end custom configuration

        # defaut login area for standard users
        main:
            switch_user:        true
            context:            user
            pattern:            .*
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
            logout:            
                path:           /admin/logout
                target:         /admin/login
            anonymous:          true

    access_control:
        # URL of FOSUserBundle which need to be available to anonymous users
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # -> custom access control for the admin area of the URL
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # -> end

        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: ^/admin, role: [ROLE_USER,ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/admin/dashboard, role: [ROLE_USER,ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        #- { path: ^/.*, role: ROLE_USER }   
        
        
        #Permisos a paginas
        - { path: ^/Donante/Nueva, role: [ROLE_SECRETARIA,ROLE_JEFE,ROLE_SONATA_ADMIN]}
        - { path: ^/HistorialClinico/Nuevo, role: [ROLE_SECRETARIA,ROLE_JEFE,ROLE_SONATA_ADMIN]}
        - { path: ^/donantesHA/, role: [ROLE_SECRETARIA,ROLE_JEFE,ROLE_SONATA_ADMIN]}
        - { path: ^/donaciones/, role: [ROLE_SECRETARIA,ROLE_JEFE,ROLE_SONATA_ADMIN]}
        
        - { path: ^/Curva/Nueva, role: [ROLE_LABORATORISTA,ROLE_JEFE,ROLE_SONATA_ADMIN]}
        - { path: ^/AnalisisMicro/Nuevo, role: [ROLE_LABORATORISTA,ROLE_JEFE,ROLE_SONATA_ADMIN]}
        - { path: ^/frascos/analisis, role: [ROLE_LABORATORISTA,ROLE_JEFE,ROLE_SONATA_ADMIN]}
        - { path: ^/pasteurizacion/, role: [ROLE_LABORATORISTA,ROLE_JEFE,ROLE_SONATA_ADMIN]}
        - { path: ^/blhtemppasteurizacion/, role: [ROLE_LABORATORISTA,ROLE_JEFE,ROLE_SONATA_ADMIN]}
        - { path: ^/frascos/analisis, role: [ROLE_LABORATORISTA,ROLE_JEFE,ROLE_SONATA_ADMIN]}
        
        - { path: ^/InfoPublica/, role: [ROLE_PEDIATRA,ROLE_JEFE,ROLE_SONATA_ADMIN]}
        
        - { path: ^/Mantenimiento/Usuarios, role: [ROLE_SONATA_ADMIN]}
        
        - { path: ^/pacientes/, role: [ROLE_JEFE,ROLE_SONATA_ADMIN]}
        - { path: ^/pacientesreceptores/, role: [ROLE_JEFE,ROLE_SONATA_ADMIN]}
        - { path: ^/receptores_solicitud, role: [ROLE_JEFE,ROLE_SONATA_ADMIN]}
        
        
        
        
        
        