parameters:
#    siblhmenu.example.class: siblh\menuBundle\Example

services:
#    siblhmenu.example:
#        class: %siblhmenu.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
